### ISSUE TITLE
https issue on the website?

### ISSUE THREAD

**Issue by yever** [calebegg/codewich#3]
I saw this project yesterday on reddit, and today I can't enter the site.
As a side note, I wasn't able to run it locally either...

This is what I get:
![screenshot from 2017-03-29 09-44-26](https://cloud.githubusercontent.com/assets/10565807/24443816/6bcb4e32-1464-11e7-93e1-d06fea171bdf.png)

**Comment by calebegg** [comment]
Are you still seeing this? It seems to be working for me. I never noticed an outage.

What was the problem when running it locally? You'll have to run a local webserver to run it locally -- you can't just open index.html in a browser. Perhaps I should include some instructions.

**Comment by calebegg** [comment]
Feel free to reopen if you can clarify.
