### ISSUE TITLE
Feature request: "Share" button to update the url only on demand

### ISSUE THREAD

**Issue by tbosch** [calebegg/codewich#5]
Right now, the url is updated on each keypress. This seems to slow down the typing a bit.
The typescript playground solved this by having a "Share" button, and not updating the url until this button is clicked.

**Comment by calebegg** [comment]
I like the idea of the URL being live, so I changed it to make the URL updates from a worker.

However, URL updates are <1ms on my machine, so if you felt much more slowness than that, it might just be Monaco.

**Comment by tbosch** [comment]
Nice!

On Sun, Jun 4, 2017 at 7:23 PM, Caleb Eggensperger <notifications@github.com
